name: Continuous Integration (CI)

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'src/**'

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

  build:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4
        
      - name: Configurar Oracle OpenJDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'oraclejdk'

      - name: Rodar o build com Maven
        run: mvn clean install

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Oracle OpenJDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'oraclejdk'

      - name: Rodar os testes automatizados
        run: mvn test
