name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Temurin JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'

      - name: Exibir mensagem "Pipeline iniciado com sucesso"
        run: echo "Pipeline iniciado com sucesso"
