name: Criar Issue em Caso de Falha

on:
  workflow_dispatch:

permissions:
  issues: write

jobs:
  verificar-variaveis:
    runs-on: ubuntu-latest

    steps:
      - name: Simular verificação de variável obrigatória
        id: verificar
        run: |
          if [ -z "${{ vars.ENV_DEPLOY }}" ]; then
            echo "variavel_faltando=true" >> $GITHUB_OUTPUT
          else
            echo "variavel_faltando=false" >> $GITHUB_OUTPUT
          fi

      - name: Criar issue se variável estiver ausente
        if: steps.verificar.outputs.variavel_faltando == 'true'
        run: |
          curl -X POST https://api.github.com/repos/${{ github.repository }}/issues \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github+json" \
          -d '{
            "title": "Variável de ambiente ausente",
            "body": "A variável `ENV_DEPLOY` não está definida. Isso pode causar falha no deploy.",
            "labels": ["bug", "automated"]
          }'
