name: Lint and Test

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Temurin JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Rodar análise com Checkstyle
        run: mvn checkstyle:check || echo "Checkstyle falhou"

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Temurin JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Rodar testes automatizados
        run: mvn test
