name: Pipeline com Variáveis e Segredos

on:
  workflow_dispatch:

jobs:
  exemplo-variaveis-secrets:
    runs-on: [self-hosted, windows]

    steps:
      - name: Exibir modo da aplicação
        run: echo "Modo da aplicação: ${{ vars.APP_MODE }}"

      - name: Exibir e-mail de suporte
        run: echo "Suporte: ${{ vars.SUPPORT_EMAIL }}"

      - name: Simular acesso autenticado com token (simulado)
        run: echo "Usando PROD_TOKEN para autenticação segura"
        env:
          TOKEN: ${{ secrets.PROD_TOKEN }}

      - name: Mostrar valor do token (somente para debug, nunca faça isso em produção!)
        run: echo "Token = $env:TOKEN"
        if: false
